#
# config for MultiQC
#
#################################################################

skip_generalstats: true
read_count_multiplier: 0.000001
read_count_prefix: 'M'
read_count_desc: 'millions'
log_filesize_limit: 2000000000

###################################
## Custom content
custom_data:
    my_stats:
        file_format: 'csv'
        section_name: 'General Metrics'
        description: ' of sequenced data.'
        plot_type: 'table'
        pconfig:
            namespace: 'stats'
            id: 'stats'
            title: 'General Statistics'
            save_file: true
            col1_header: 'Sample_ID'
        headers:
            Sample_name:
              title: 'Sample Name'
              scale: false
              format: '{:.0f}'
              placement: 1000
            Number_of_reads:
              title: 'Total Fragments'
              scale: 'RdYlGn'
              format: '{:,.0f}'
              placement: 2000
            Number_of_aligned_reads:
              title: 'Aligned Reads'
              scale: 'RdYlGn'
              format: '{:,.0f}'
              hidden: true
              placement: 3000
            Percent_of_aligned_reads:
              title: 'Aligned Reads (%)'
              min: 0
              max: 100
              scale: 'RdYlGn'
              suffix: '%'
              format: '{:,.1f}'
              placement: 3500
            Number_of_mito:
              title: 'Mitochondrial Reads'
              scale: 'RdYlGn'
              format: '{:,.0f}'
              hidden: true
              placement: 4000
            Percent_of_mito:
              title: 'Mitochondrial Reads (%)'
              min: 0
              max: 100
              scale: 'RdYlGn'
              suffix: '%'
              format: '{:,.1f}'
              placement: 4500
            Number_of_hq_mapped_reads:
              title: 'High-Quality Alignment'
              description: 'High-Quality Mapped Reads (mapQ > 10)'
              scale: 'RdYlGn'
              format: '{:,.0f}'
              hidden: true
              placement: 5000
            Percent_of_hq_mapped_reads:
              title: 'High-Quality Alignment (%)'
              description: 'High-Quality Mapped Reads (mapQ > 10)'
              min: 0
              max: 100
              scale: 'RdYlGn'
              format: '{:,.1f}'
              suffix: '%'
              placement: 6000
            Number_of_lq_mapped_reads:
              title: 'Low-Quality Alignment'
              description: 'Low-Quality Mapped Reads (mapQ < 10)'
              scale: 'RdYlGn'
              format: '{:,.0f}'
              hidden: true
              placement: 7000
            Percent_of_lq_mapped_reads:
              title: 'Low-Quality Alignment (%)'
              description: 'Low-Quality Mapped Reads (mapQ < 10)'
              min: 0
              max: 100
              scale: 'RdYlGn'
              format: '{:,.1f}'
              suffix: '%'
              placement: 8000
            Number_of_duplicates:
              title: 'Duplicates'
              scale: 'RdYlGn'
              format: '{:,.0f}'
              hidden: true
              placement: 9000
            Percent_of_duplicates:
              title: 'Duplicates (%)'
              min: 0
              max: 100
              scale: 'RdYlVBu'
              format: '{:,.1f}'
              suffix: '%'
              placement: 10000
            Number_of_usable_reads:
              title: 'Final Usable Reads Number'
              scale: 'RdYlGn'
              format: '{:,.0f}'
              hidden: true
              placement: 11000
            Percent_of_usable_reads:
              title: 'Final Usable Reads (%)'
              min: 0
              max: 100
              scale: 'RdYlVBu'
              format: '{:,.1f}'
              suffix: '%'
              placement: 12000
            TSS_enrichment:
              title: 'TSS Enrichment'
              description: 'TSS Enrichment Score'
              scale: 'RdYlGn'
              format: '{:,.2f}'
              placement: 12500
            Fraction_of_reads_in_peaks:
              min: 0
              max: 1
              title: 'FRiP'
              description: 'Faction of reads in peaks'
              scale: 'RdYlGn'
              format: '{:,.2f}'
              placement: 13000

    bwa_logs:
        file_format: 'tsv'
        section_name: 'Bwa-mem'
        description: 'statistics on aligned data. Number of unique and multiple mapped reads, as well unmapped reads are reported.'
        plot_type: 'bargraph'
        pconfig:
            namespace: 'bwalogs'
            title: 'Reads Alignment'
            id: 'bwalogs'
            scale: 'Set1'

sp:
  my_stats:
      fn: '*.stats'
  bwa_logs:
      fn: '*bwa.mqc'

table_cond_formatting_rules:
    Percent_of_mito:
        pass:
          - lt: 10
        warn:
          - gt: 10
        fail:
          - gt: 30
    Percent_of_aligned_reads:
        pass:
          - gt: 80
        warn:
          - lt: 80
        fail:
          - lt: 50
    Percent_of_duplicates:
        pass:
          - lt: 25
        warn:
          - gt: 25
        fail:
          - gt: 50
    Percent_of_usable_reads:
        pass:
          - gt: 50
        warn:
          - lt: 50
        fail:
          - lt: 25
    TSS_enrichment:
        pass:
          - gt: 0.399
        warn:
          - lt: 0.40
        fail:
          - lt: 0.25
    Fraction_of_reads_in_peaks:
        pass:
          - gt: 0.01
        fail:
          - lt: 0.01


###############################
## Modules 

module_order:
   - fastqc
   - bowtie2:
      name: 'Bowtie2'
      info: 'alignment of raw sequencing reads on the reference genome.'
   - picard:
      name: 'Fragment size'
      info: ' shows nucleosome occupancy. Fragment lengths lower than 100bp usually represent nucleosome free regions. Then, the fragment size distribution is expected to have a clear periodicity related to nucleosome occupancy (mono-, di-, tri-nucleosome, etc.)'
   - preseq:
      name: 'Sequencing Complexity'
      info: 'estimates the complexity of a library, showing how many additional unique reads are sequenced for increasing total read count. A shallow curve indicates complexity saturation. The dashed line shows a perfectly complex library where total reads = unique reads. The presented graph shows extrapolated curves up to 200M sequencing reads.'
   - macs2
   - deeptools:
      name: 'NFR enrichment'
      info: '- Nucleome-Free Regions (NFR) enrichment around Transcription Start Sites (TSS). Only fragments with a size lower than 100 bp are considered.'
      anchor: 'deeptools-NFR'
      path_filters:
        - '*NFR.plotProfile_corrected.tab'
      path_filters_exclude:
        - '*NUC.plotProfile_corrected.tab'
        - 'plotFingerprint*'
   - deeptools:
      name: 'NBR enrichment'
      info: '- Mono/di/tri-nucleosomes Bound Regions (NBR) enrichment around Transcription Start Sites (TSS). Fragments with a size between 180 and 437 bp are considered.'
      anchor: 'deeptools-NUC'
      path_filters:
        - '*NBR.plotProfile_corrected.tab'
   - deeptools:
      name: 'Fingerprint'
      path_filters_exclude:
        - '*plotProfile_corrected.tab'
   - homer

report_section_order:
  my_stats:
    order: 1000
  fastqc:
    order: 900
  bwa_logs:
    order: 800
  bowtie2:
    order: 790
  picard:
    order: 600
  peak_count:
    order: -1300
  peak_annotation:
    order: -1500
  deeptools_correlation:
    order: -1600
  deeptools_fingerprint:
    order: -1700
  read_distribution_profile_plot:
    order: -1900
  software_versions:
    order: -2000
  summary:
    order: -2100

#############################
## Removed plots
remove_sections :
  - fastqc_sequence_counts
  - fastqc_per_sequence_quality_scores
  - fastqc_overrepresented_sequences
  - fastqc_status_checks
  - plotFingerprint
  - picard-markduplicates

fn_ignore_files:
  - '*FRiP*'

fn_clean_exts:
    - '_bwa.log'
    - '_bowtie2.log'
    - 'Log.final.out'
    - '_sorted.bam'
    - '_peaks.count_mqc'

#############################
## Display

custom_plot_config:
   bwalogs:
      Unmapped:
         color: '#A6ACAF'
   picard_insert_size:
      cpswitch: False
      xmax: 1000
      logswitch: True
      logswitch_active: False
   read_distribution_profile:
      title: 'Signal enrichment around TSS'

plots_force_interactive: True
